/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlackView: typeof import('./components/black-view/black-view.vue')['default']
    CommonPage: typeof import('./components/common-page/common-page.vue')['default']
    MySwiper: typeof import('./components/my-swiper/my-swiper.vue')['default']
    NavBar: typeof import('./components/nav-bar/nav-bar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpinLoading: typeof import('./components/spin-loading/spin-loading.vue')['default']
    TabBar: typeof import('./components/tab-bar/tab-bar.vue')['default']
  }
}
